name: Jalankan Bot Lamaran Otomatis

on:
  workflow_dispatch:

jobs:
  run-python-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Mengambil kode dari repositori
      uses: actions/checkout@v4

    - name: Menyiapkan Python di server GitHub
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Memasang modul pendukung jika ada
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Eksekusi Kirim Email Lamaran
      env:
        EMAIL_PENGIRIM: ${{ secrets.EMAIL_PENGIRIM }}
        PASSWORD_APLIKASI: ${{ secrets.PASSWORD_APLIKASI }}
      run: python email_sender.py
